export const PERMISSION_CATALOG = [
  'tasks.view',
  'tasks.create',
  'tasks.assign',
  'tasks.edit_own',
  'tasks.edit_all',
  'tasks.delete',
  'finance.view',
  'finance.create',
  'finance.view_summary',
  'finance.view_all',
  'expenses.create',
  'expenses.approve',
  'transactions.export',
  'members.view',
  'members.invite',
  'members.edit_role',
  'members.remove',
  'members.manage',
  'roles.manage',
  'projects.view',
  'projects.create',
  'projects.manage',
  'projects.archive',
  'reports.view',
  'reports.view_operational',
  'reports.view_financial',
  'reports.export',
  'settings.view',
  'settings.manage',
  'workspace.billing_manage',
] as const;

export type PermissionKey = (typeof PERMISSION_CATALOG)[number];
